### ISSUE TITLE
Class parameters missing

### ISSUE THREAD

**Issue by notFloran** [asdoria/AsdoriaSyliusFacetFilterPlugin#7]
After I install the bundle in my project, I have the following errors: 

```
You have requested a non-existent parameter "asdoria.model.facet.class"
You have requested a non-existent parameter "asdoria.model.facet_filter.class". Did you mean this: "asdoria.model.facet.class"?
You have requested a non-existent parameter "asdoria.model.facet_group.class". Did you mean one of these: "asdoria.model.facet.class", "asdoria.model.facet_filter.class"?
```

I have added this lines to `services.yaml` to fix the errors: 

```
parameters:
    asdoria.model.facet.class: Asdoria\SyliusFacetFilterPlugin\Entity\Facet
    asdoria.model.facet_filter.class: Asdoria\SyliusFacetFilterPlugin\Entity\FacetFilter
    asdoria.model.facet_group.class: Asdoria\SyliusFacetFilterPlugin\Entity\FacetGroup
```
